Develop : Corrections
eZmaxinc/eZmax-SDK-php-sample pull request #13
Opened 2021-03-02 18:40 UTC by Patfreeze

Corrections of names. Added some missing require for the connector

2021-03-02 21:49 UTC, Herrick19 commented on global/customer/getEndpoint.php
> + * Retrieve the URL for stg ca-central-1
Pas pertinent

2021-03-02 21:50 UTC, Herrick19 commented on webhooks/Management/UserCreated.php
> +//var_dump(get_class_methods($objUser));exit;
Attention de laisser les samples propres

2021-03-02 21:51 UTC, Herrick19 commented on webhooks/Management/UserCreated.php
>  //This object contain Ezsign User information.
"contains", pas "contain"... Surement plusieurs fichiers à corriger

2021-03-02 21:51 UTC, Herrick19 requested changes
Svp corriger les points mentionnés

2021-03-03 19:41 UTC, Patfreeze commented
Dans un nouveau pull request

2021-03-03 19:41 UTC, closed without merging